# Generated by Django 5.0.4 on 2025-03-15 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
