# Generated by Django 5.0.4 on 2025-03-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0002_delete_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/img/')),
                ('location', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('profilBanner', models.ImageField(upload_to='static/img/')),
                ('fullname', models.CharField(max_length=50)),
            ],
        ),
    ]
