# Generated by Django 5.1.4 on 2025-04-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='ish',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
