# Generated by Django 5.1.7 on 2025-04-23 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_profil_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='user',
        ),
    ]
