# Generated by Django 5.0.4 on 2025-03-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkedIn', '0002_postimg_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimg',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
