# Generated by Django 5.1.4 on 2025-04-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkedIn', '0007_post_delete_postimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
